import { Add, Blend, Short } from './classes.js';

export const wordList = [
    new Short ("sad", "a"),
    new Short ("mad", "a"),
    new Short ("ham", "a"),
    new Short ("fan", "a"),
    new Short ("hat", "a"),
    new Short ("sat", "a"),
    new Short ("mat", "a"),
    new Short ("cap", "a"),
    new Short ("gas", "a"),
    new Short ("pan", "a"),
    new Short ("cat", "a"),
    new Short ("bat", "a"),
    new Short ("tag", "a"),
    new Short ("dad", "a"),
    new Short ("zap", "a"),
    new Short ("rat", "a"),
    new Short ("map", "a"),
    new Short ("yak", "a"),
    new Short ("man", "a"),
    new Short ("can", "a"),
    new Short ("ant", "a"),
    new Short ("fat", "a"),
    new Short ("bag", "a"),

    new Short ("dig", "i"),
    new Short ("sit", "i"),
    new Short ("kit", "i"),
    new Short ("lid", "i"),
    new Short ("pig", "i"),
    new Short ("lip", "i"),
    new Short ("fin", "i"),
    new Short ("fit", "i"),
    new Short ("hip", "i"),
    new Short ("win", "i"),
    new Short ("rip", "i"),
    new Short ("hit", "i"),
    new Short ("big", "i"),
    new Short ("zip", "i"),

    new Short ("bed", "e"),
    new Short ("pet", "e"),
    new Short ("pen", "e"),
    new Short ("ten", "e"),
    new Short ("web", "e"),
    new Short ("red", "e"),
    new Short ("gem", "e"),
    new Short ("get", "e"),
    new Short ("men", "e"),
    new Short ("jet", "e"),
    new Short ("vet", "e"),
    new Short ("set", "e"),
    new Short ("net", "e"),
    new Short ("hen", "e"),
    new Short ("beg", "e"),
    new Short ("wet", "e"),
    new Short ("leg", "e"),

    new Short ("hop", "o"),
    new Short ("top", "o"),
    new Short ("pot", "o"),
    new Short ("jog", "o"),
    new Short ("mop", "o"),
    new Short ("dog", "o"),
    new Short ("dot", "o"),
    new Short ("hot", "o"),
    new Short ("fog", "o"),
    new Short ("log", "o"),
    new Short ("not", "o"),
    new Short ("old", "o"),

    new Short ("gun", "u"),
    new Short ("bun", "u"),
    new Short ("cub", "u"),
    new Short ("sub", "u"),
    new Short ("mud", "u"),
    new Short ("hut", "u"),
    new Short ("sun", "u"),
    new Short ("cut", "u"),
    new Short ("tug", "u"),
    new Short ("tub", "u"),
    new Short ("bug", "u"),
    new Short ("fun", "u"),
    new Short ("rug", "u"),
    new Short ("run", "u"),
    new Short ("nut", "u"),
    new Short ("bud", "u"),
    new Short ("up", "u"),
    new Short ("cup", "u"),
    new Short ("mug", "u"),
    new Short ("gum", "u"),
    new Short ("rub", "u"),

    new Add('back', "a"),

    new Add('neck', "e"),
    new Add('nest', "e"),
    new Add('tent', "e"),
    new Add('vest', "e"),

    new Add('brick', "i"),
    new Add('clip', "i"),
    new Add('crib', "i"),
    new Add('flip', "i"),
    new Add('slip', "i"),
    new Add('spit', "i"),
    new Add('split', "i"),
    new Add('twin', "i"),

    new Add('corn', "o"),
    new Add('crop', "o"),
    new Add('horn', "o"),
    new Add('open', "o"),
    new Add('sock', "o"),
    new Add('stop', "o"),

    new Add('duck', "u"),
    new Add('push', "u"),

    new Blend("chip", "ch"),
    new Blend("chop", "ch"),
    new Blend("chest", "ch"),
    new Blend("bench", "ch"),
    new Blend("lunch", "ch"),
    new Blend("branch", "ch"),
    new Blend("march", "ch"),
    new Blend("witch", "ch"),
    new Blend("watch", "ch"),
    new Blend("pinch", "ch"),
    new Blend("catch", "ch"),
    new Blend("chimp", "ch"),
    new Blend("punch", "ch"),
    new Blend("lunch", "ch"),

    new Blend("brush", "sh"),
    new Blend("shot", "sh"),
    new Blend("shirt", "sh"),
    new Blend("shot", "sh"),
    new Blend("shower", "sh"),
    new Blend("trash", "sh"),
    new Blend("smash", "sh"),
    new Blend("shred", "sh"),
    new Blend("crash", "sh"),
    new Blend("shovel", "sh"),
    
    new Blend("black", "ck"),
    new Blend("rock", "ck"),
    new Blend("chick", "ck"),
    new Blend("stick", "ck"),
    new Blend("lick", "ck"),
    new Blend("stick", "ck"),
    new Blend("trick", "ck"),
    new Blend("pick", "ck"),
    new Blend("lock", "ck"),
    new Blend("clock", "ck"),
    new Blend("stack", "ck"),
    new Blend("rack", "ck"),
    new Blend("tack", "ck"),
    new Blend("block", "ck"),
    new Blend("thick", "ck"),
    new Blend("jacket", "ck"),
    new Blend("rocket", "ck"),

    new Blend("stamp", "st"),
    new Blend("strap", "st"),
    new Blend("stamp", "st"),
    new Blend("stand", "st"),
    
    new Blend("clap", "cl"),
    new Blend("club", "cl"),
    new Blend("clown", "cl"),
    new Blend("plug", "pl"),
    new Blend("slip", "sl"),
    new Blend("plus", "pl"),
    new Blend("flower", "fl"),
    new Blend("clam", "cl"),
    new Blend("blimp", "bl"),

    new Blend("ring", "ng"),
    new Blend("wing", "ng"),
    new Blend("swing", "ng"),
    new Blend("sing", "ng"),
    new Blend("sting", "ng"),
    new Blend("strong", "ng"),
    new Blend("song", "ng"),

    new Blend("quit", "qu"),
    new Blend("quiet", "qu"),
    new Blend("quick", "qu"),
    new Blend("quilt", "qu"),
    new Blend("question", "qu"),
    new Blend("think", "th"),
    new Blend("thorn", "th"),

    new Blend("whip", "wh"),
    new Blend("whisper", "wh"),
    new Blend("when", "wh"),
    new Blend("who", "wh"),

    new Blend("nine", "e"),
    new Blend("smile", "e"),
    new Blend("time", "e"),
    new Blend("name", "e"),
    new Blend("crane", "e"),
    new Blend("drive", "e"),
    new Blend("frame", "e"),
    new Blend("skate", "e"),
    new Blend("cake", "e"),
    new Blend("bite", "e"),
    new Blend("home", "e"),
    new Blend("bone", "e"),
    new Blend("snake", "e"),
    new Blend("whale", "e"),
    new Blend("rice", "e"),
    new Blend("june", "e"),
    new Blend("rake", "e"),
    new Blend("close", "e"),
    new Blend("bake", "e"),
    new Blend("space", "e"),
    new Blend("clover", "e"),
    new Blend("bake", "e"),
    new Blend("same", "e"),
];