export const songData = [
	{
		school: 'senri',
		parents: [
			{
				title: 'April',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'May',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'June',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
		],
		'3-5': [
			{
				title: 'April',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'May',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'June',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
		],
		active: [
			{
				title: 'April',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'May',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'June',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
		],
	},
	{
		school: 'uehon',
		parents: [
			{
				title: 'April',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'May',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'June',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
		],
		'3-5': [
			{
				title: 'April',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'May',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'June',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
		],
		active: [
			{
				title: 'April',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'May',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'June',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
		],
	},
	{
		school: 'nishinomiya',
		parents: [
			{
				title: 'April',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'May',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'June',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
		],
		'3-5': [
			{
				title: 'April',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'May',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'June',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
		],
		active: [
			{
				title: 'April',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'May',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
			{
				title: 'June',
				hello: 'asdsad - asdasd',
				tpr: 'asdasd - asdasd',
				body: 'asdsad- asdasd',
				monthly: 'asdasd - asd',
				goodbye: 'matt',
			},
		],
	},
];
